'use strict';
const $ = id => document.getElementById(id);
let lang = localStorage.getItem('awg3-language') === 'en' ? 'en' : 'ru';
let csrf = '', state = null, busy = false;
const en = {local:'Local control panel',logout:'Sign out',welcome:'Your VPN. Your router.',loginHint:'Use the panel password created during setup.',password:'Panel password',signin:'Sign in',routerRuns:'The panel and VPN run on the router. This browser is only a controller.',workspace:'CONNECTION WORKSPACE',subtitle:'Profiles, status and controls on your router.',refresh:'Refresh',overview:'Overview',profiles:'Profiles',diagnostics:'Diagnostics',settings:'Settings',control:'VPN CONTROLS',connection:'Service controls',controlHint:'Start and stop affect all service profiles.',start:'Start VPN',stop:'Stop',routesHint:'Manage routes and policies in the Netcraze interface.',startup:'AFTER REBOOT',autostart:'VPN autostart',enable:'Enable',disableStop:'Disable and stop VPN',tunnels:'Tunnels',handshakeHint:'Engine availability and a handshake are different signals. A recent handshake does not replace traffic and PingCheck verification.',import:'Import profile',importHint:'Choose .vpn, .txt or .conf, or paste a key. Use a separate profile per device.',target:'Profile name',targetHint:'To replace, use the existing name without .conf. New profiles can be added while the service is stopped.',file:'Profile file',orKey:'Or a vpn:// key',ipv4:'IPv4 only. Firmware DNS is retained. Verify connectivity to the new server afterwards.',apply:'Validate and apply',backups:'Backups',backupHint:'A backup is saved before replacement. Restore applies it to the original profile.',pingHint:'Firmware connectivity checks through VPN. Current status below, followed by new check settings.',log:'Service log',load:'Load',logHint:'Recent messages with key filtering. No profiles are displayed here.',watchdog:'Watchdog and inbox',watchdogHint:'Checks the local engine and processes inbox files about every 30 seconds while the service runs.',disable:'Disable',changePassword:'Change panel password',currentPassword:'Current password',newPassword:'New password · at least 12 characters',repeatPassword:'Repeat new password',savePassword:'Save password',footer:'Local. On your router.',enabled:'Enabled',disabled:'Disabled',empty:'No profiles yet. Open Profiles to import one.',noBackups:'No backups yet.',engine:'Engine available',unavailable:'Engine unavailable',stopped:'Service stopped',handshake:'Last handshake',received:'Received',sent:'Sent',never:'Not yet',restore:'Restore',working:'Applying…',confirm:'Apply this action? ',confirmImport:'Replace/import this profile: ',confirmRestore:'Restore this backup: ',choose:'Choose a file OR paste a key.',size:'Maximum file size is 4 MiB.',mismatch:'Passwords do not match.',updated:'Updated ',success:'Completed. Verify handshake and PingCheck.',error:'Unable to reach the panel. Check its address and router connection.'};
const ru = {enabled:'Включён',disabled:'Выключен',empty:'Профилей пока нет. Откройте «Профили» для импорта.',noBackups:'Резервных копий пока нет.',engine:'Движок доступен',unavailable:'Движок недоступен',stopped:'Служба остановлена',handshake:'Последний handshake',received:'Получено',sent:'Отправлено',never:'Ещё не было',restore:'Восстановить',working:'Применение…',confirm:'Выполнить действие? ',confirmImport:'Импортировать/заменить профиль: ',confirmRestore:'Восстановить резервную копию: ',choose:'Выберите файл ИЛИ вставьте ключ.',size:'Максимальный размер файла — 4 МиБ.',mismatch:'Пароли не совпадают.',updated:'Обновлено ',success:'Готово. Проверьте handshake и PingCheck.',error:'Нет связи с панелью. Проверьте адрес и подключение к роутеру.'};
Object.assign(en,{pingInterface:'VPN interface',pingDefaults:'These are recommended values for a new check, not the current settings. Apply replaces the check assigned to this VPN only.',pingHost:'IPv4 test address',pingInterval:'Interval, seconds',pingTimeout:'Timeout, seconds',pingFails:'Failures before disabling',pingSuccess:'Successes before recovery',pingBehavior:'ICMP mode, without restarting the interface. ISP fallback also depends on Netcraze routes and policies.',pingApply:'Enable / apply',pingDisable:'Disable check',pingSaveHint:'Use the button below to retain changes after reboot. It saves the entire current firmware configuration, including changes outside this panel.',pingSave:'Save router configuration',pingConfirm:'Replace the PingCheck settings for ',pingSaveConfirm:'Save the entire current router configuration, including changes outside this panel?',pingNone:'No managed VPN interface. Start VPN first.'});
Object.assign(ru,{pingConfirm:'Заменить настройки PingCheck для ',pingSaveConfirm:'Сохранить всю текущую конфигурацию роутера, включая изменения вне этой панели?',pingNone:'Нет управляемого VPN-интерфейса. Сначала запустите VPN.'});
Object.assign(en,{connected:'Connected',disconnected:'Disconnected',unverified:'Connection not verified',partial:'Some tunnels unavailable',rename:'Rename',renamePrompt:'Display name (1–64 Latin letters, digits, spaces, dot, dash or underscore). Profile filename stays unchanged:',profileId:'Profile file: ',checkNeeded:'Enable PingCheck in Diagnostics to verify connectivity.'});
Object.assign(ru,{connected:'Подключено',disconnected:'Отключено',unverified:'Связь не проверена',partial:'Часть туннелей недоступна',rename:'Переименовать',renamePrompt:'Отображаемое имя (1–64: латиница, цифры, пробелы, точка, дефис или подчёркивание). Имя файла профиля не меняется:',profileId:'Файл профиля: ',checkNeeded:'Для проверки связи включите PingCheck в разделе «Диагностика».'});
const original = new Map([...document.querySelectorAll('[data-i18n]')].map(el => [el,el.textContent]));
const t = key => (lang === 'en' ? en[key] : ru[key]) || key;
function translate(){document.documentElement.lang=lang;$('language').textContent=lang==='ru'?'EN':'RU';for(const [el,text] of original)el.textContent=lang==='en'?(en[el.dataset.i18n]||text):text;if(state)render(state);}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);$('notice').hidden=false;}
function signedIn(yes){$('login').hidden=yes;$('dashboard').hidden=!yes;$('logout').hidden=!yes;if(!yes){csrf='';state=null;$('profile-key').value='';$('profile-file').value='';$('current-password').value='';$('new-password').value='';$('repeat-password').value='';}}
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',credentials:'same-origin',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await response.json();if(!response.ok){if(response.status===401)signedIn(false);throw new Error(result.error||t('error'));}return result;}
async function perform(fn){if(busy)return;busy=true;document.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=true);try{await fn();}catch(error){notice(error.message||t('error'),true);}finally{busy=false;document.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=false);updateButtons();}}
function bytes(n){for(const unit of ['B','KiB','MiB','GiB','TiB']){if(n<1024||unit==='TiB')return `${n.toFixed(n<10?1:0)} ${unit}`;n/=1024;}}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function updateButtons(){
 if(!state)return;
 const rules={up:state.running,stop:!state.running&&!state.started,enable:state.enabled,disable:!state.enabled};
 for(const [action,disabled] of Object.entries(rules))document.querySelector('[data-action="'+action+'"]').disabled=busy||state.busy||disabled;
}
function render(s){renderPingInterfaces(s);updateButtons();
 const connections=s.tunnels.map(tunnel=>tunnel.connection);
 const connection=!connections.length||connections.every(x=>x==='disconnected')?'disconnected':connections.every(x=>x==='connected')?'connected':connections.some(x=>x==='unverified')?'unverified':'partial';
 $('connection-state').textContent=t(connection);$('connection-state').classList.toggle('status-off',connection!=='connected');$('enabled-state').textContent=t(s.enabled?'enabled':'disabled');$('watchdog-state').textContent=t(s.watchdog?'enabled':'disabled');$('pingcheck').textContent=s.pingcheck;$('updated').textContent=t('updated')+new Date().toLocaleTimeString(lang);$('tunnel-list').replaceChildren();if(!s.tunnels.length)$('tunnel-list').append(node('p',t('empty'),'muted'));for(const tunnel of s.tunnels){const card=node('article',undefined,'card');card.append(node('div','Amnezia VPN · '+tunnel.interface,'eyebrow'),node('h2',tunnel.name||tunnel.profile),node('span',t(tunnel.connection),'tag'+(tunnel.connection!=='connected'?' off':'')));
if(tunnel.connection==='unverified')card.append(node('p',t('checkNeeded'),'caption'));
const rename=node('button',t('rename'));rename.disabled=busy;
rename.addEventListener('click',()=>{const label=prompt(t('renamePrompt'),tunnel.name||tunnel.profile);if(label===null)return;perform(async()=>{const result=await api('/api/action',{action:'rename',name:tunnel.profile,label:label.trim()});notice(result.message);await refresh();});});
card.append(node('p',t('profileId')+tunnel.profile+'.conf','caption'),rename);const metrics=node('div',undefined,'metrics');for(const [label,value] of [['handshake',tunnel.handshake?new Date(tunnel.handshake*1000).toLocaleString(lang):t('never')],['received',bytes(tunnel.received)],['sent',bytes(tunnel.sent)]]){const metric=node('div',undefined,'metric');metric.append(node('strong',value),node('span',t(label)));metrics.append(metric);}card.append(metrics);$('tunnel-list').append(card);}
$('profile-names').replaceChildren(...s.profiles.map(name=>{const option=node('option');option.value=name;return option;}));$('backup-list').replaceChildren();if(!s.backups.length)$('backup-list').append(node('p',t('noBackups'),'muted'));for(const backup of s.backups){const row=node('div',undefined,'backup-row'),info=node('div',backup.profile),button=node('button',t('restore'));info.append(node('small',new Date(backup.time*1000).toLocaleString(lang)));button.addEventListener('click',()=>{if(confirm(t('confirmRestore')+backup.id))perform(async()=>{const result=await api('/api/action',{action:'restore',backup:backup.id});notice(result.message);await refresh();});});row.append(info,button);$('backup-list').append(row);}}
async function refresh(){if(!csrf)return;state=await api('/api/status');render(state);}
$('language').addEventListener('click',()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('awg3-language',lang);translate();});
$('login-form').addEventListener('submit',event=>{event.preventDefault();perform(async()=>{const password=$('password').value;$('password').value='';const result=await api('/api/login',{password});csrf=result.csrf;signedIn(true);$('notice').hidden=true;await refresh();if(state.profiles.length)$('profile-name').value=state.profiles[0];});});
$('logout').addEventListener('click',()=>perform(async()=>{await api('/api/logout',{});signedIn(false);$('notice').hidden=true;}));
$('refresh').addEventListener('click',()=>perform(refresh));
for(const tab of document.querySelectorAll('[data-view]'))tab.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==tab.dataset.view);document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el===tab));});
for(const button of document.querySelectorAll('[data-action]'))button.addEventListener('click',()=>{if(!confirm(t('confirm')+button.textContent))return;perform(async()=>{notice(t('working'));const result=await api('/api/action',{action:button.dataset.action});notice(result.message||t('success'));await refresh();});});
$('import-form').addEventListener('submit',event=>{event.preventDefault();const file=$('profile-file').files[0],key=$('profile-key').value.trim(),name=$('profile-name').value.trim();if(Boolean(file)===Boolean(key)){notice(t('choose'),true);return;}if(file&&file.size>4*1024*1024){notice(t('size'),true);return;}if(!confirm(t('confirmImport')+name))return;perform(async()=>{const raw=file?new Uint8Array(await file.arrayBuffer()):new TextEncoder().encode(key);if(raw.length>4*1024*1024)throw Error(t('size'));let binary='';for(let n=0;n<raw.length;n+=8192)binary+=String.fromCharCode(...raw.subarray(n,n+8192));notice(t('working'));const result=await api('/api/action',{action:'import',name,data:btoa(binary)});$('profile-key').value='';$('profile-file').value='';notice(result.message||t('success'));await refresh();});});
$('load-log').addEventListener('click',()=>perform(async()=>{$('service-log').textContent=(await api('/api/log')).log||'—';}));
$('password-form').addEventListener('submit',event=>{event.preventDefault();if($('new-password').value!==$('repeat-password').value){notice(t('mismatch'),true);return;}perform(async()=>{const result=await api('/api/password',{current:$('current-password').value,password:$('new-password').value});signedIn(false);notice(result.message);});});
function renderPingInterfaces(s){
 const select=$('ping-interface'),current=select.value;
 const options=s.tunnels.map(tunnel=>{const option=node('option',(tunnel.name||tunnel.profile)+' · '+tunnel.interface);option.value=tunnel.interface;return option;});
 if(!options.length){const option=node('option',t('pingNone'));option.value='';options.push(option);}
 select.replaceChildren(...options);
 if(s.tunnels.some(tunnel=>tunnel.interface===current))select.value=current;
}
$('ping-form').addEventListener('submit',event=>{
 event.preventDefault();const iface=$('ping-interface').value;if(!iface){notice(t('pingNone'),true);return;}
 if(!confirm(t('pingConfirm')+iface+'?'))return;
 const body={action:'pingcheck-apply',interface:iface,host:$('ping-host').value.trim(),'update-interval':Number($('ping-interval').value),timeout:Number($('ping-timeout').value),'max-fails':Number($('ping-fails').value),'min-success':Number($('ping-success').value)};
 perform(async()=>{const result=await api('/api/action',body);notice(result.message);await refresh();});
});
$('ping-disable').addEventListener('click',()=>{
 const iface=$('ping-interface').value;if(!iface){notice(t('pingNone'),true);return;}
 if(confirm(t('confirm')+$('ping-disable').textContent+' · '+iface+'?'))perform(async()=>{const result=await api('/api/action',{action:'pingcheck-disable',interface:iface});notice(result.message);await refresh();});
});
$('ping-save').addEventListener('click',()=>{if(confirm(t('pingSaveConfirm')))perform(async()=>{const result=await api('/api/action',{action:'pingcheck-save'});notice(result.message);});});
translate();
(async()=>{try{csrf=(await api('/api/session')).csrf;signedIn(true);await refresh();if(state.profiles.length)$('profile-name').value=state.profiles[0];}catch{signedIn(false);}})();
setInterval(()=>{if(csrf&&!busy&&!document.hidden)refresh().catch(error=>notice(error.message,true));},15000);
